export const data = [
    {
        id: 1,
        name: 'Test project 1',
        description: 'this is just the description for test project 1. With some random words on the end to make it a little bit longer.',
        image: '',
        createdOn: '',
        tags: [
            {id: 1, name: 'P1', description: 'highest level of priority', colour: '#ff4f4f'},
            {id: 2, name: 'P2', description: 'second highest level of priority', colour: '#ff824f'},
            {id: 3, name: 'P3', description: 'third highest level of priority', colour: '#ffc74f'},
            {id: 4, name: 'P4', description: 'second lowest level of priority', colour: '#c7ff4f'},
            {id: 5, name: 'P5', description: 'lowest level of priority', colour: '#6aff4f'},
            {id: 6, name: 'On Live', description: 'its on the live site', colour: '#1fc137'},
            {id: 7, name: 'Ready for Live', description: 'reaady to go on the live site', colour: '#c1891f'},
        ],
        columns: [
            { id: 1, name: 'Feb', positon: 0, color: '#bfbfbf'},
            { id: 2, name: 'March', positon: 1, color: '#f2f2f2'},
            { id: 3, name: 'April', positon: 2, color: '#9a0000'},
            { id: 4, name: 'May', positon: 3, color: '#9a8700'},
        ],
        tasks: [
            {
                id: 1,
                columnId: 1,
                columnPosition: 1,
                name: 'Add header',
                description: 'just a random description of task 1, but i have added some words onto the end to make the description a little longer',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [1,7],
                relations: [],
                checklist: [
                    {id: 1, description: 'blooping bloop', checked: false},
                    {id: 2, description: 'blap blap bloop', checked: true},
                    {id: 3, description: 'some text', checked: false},
                ],
                attachments: [],
                comments: []
            },
            {
                id: 2,
                columnId: 1,
                columnPosition: 2,
                name: 'Add footer',
                description: 'just a random description of task 2',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [2],
                relations: [1],
                checklist: [],
                attachments: [],
                comments: []
            },
            {
                id: 3,
                columnId: 1,
                columnPosition: 3,
                name: 'Add Newsletter',
                description: 'just a random description of task 3, then some extra text, maybe i should use lorem ipsum here?',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [1,7],
                relations: [],
                checklist: [],
                attachments: [],
                comments: []
            }
        ]
    },
    {
        id: 2,
        name: 'Test project 2',
        description: 'this is just the description for test project 2. With some random words on the end to make it a little bit longer. Then there is some more text on the end.',
        createdOn: '',
        image: 'https://picsum.photos/200',
        tags: [
            {id: 1, name: 'P1', description: 'highest level of priority', colour: '#ff4f4f'},
            {id: 2, name: 'P2', description: 'second highest level of priority', colour: '#ff824f'},
            {id: 3, name: 'P3', description: 'third highest level of priority', colour: '#ffc74f'},
            {id: 4, name: 'P4', description: 'second lowest level of priority', colour: '#c7ff4f'},
            {id: 5, name: 'P5', description: 'lowest level of priority', colour: '#6aff4f'},
            {id: 6, name: 'On Live', description: 'its on the live site', colour: '#1fc137'},
            {id: 7, name: 'Ready for Live', description: 'reaady to go on the live site', colour: '#c1891f'},
        ],
        columns: [
            { id: 1, name: 'Feb', positon: 0, color: '#bfbfbf'},
            { id: 2, name: 'March', positon: 1, color: '#f2f2f2'},
            { id: 3, name: 'April', positon: 2, color: '#9a0000'},
            { id: 4, name: 'May', positon: 3, color: '#9a8700'},
        ],
        tasks: [
            {
                id: 1,
                columnId: 1,
                columnPosition: 1,
                name: 'Add header',
                description: 'just a random description of task 1, but i have added some words onto the end to make the description a little longer',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [1,7],
                relations: [],
                checklist: [
                    {id: 1, description: 'blooping bloop', checked: false},
                    {id: 2, description: 'blap blap bloop', checked: true},
                    {id: 3, description: 'some text', checked: false},
                ],
                attachments: [],
                comments: []
            },
            {
                id: 2,
                columnId: 1,
                columnPosition: 2,
                name: 'Add footer',
                description: 'just a random description of task 2',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [2],
                relations: [1],
                checklist: [],
                attachments: [],
                comments: []
            },
            {
                id: 3,
                columnId: 1,
                columnPosition: 3,
                name: 'Add Newsletter',
                description: 'just a random description of task 3, then some extra text, maybe i should use lorem ipsum here?',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [1,7],
                relations: [],
                checklist: [],
                attachments: [],
                comments: []
            },
            {
                id: 4,
                columnId: 2,
                columnPosition: 1,
                name: 'Lorem ipsum dolor sit amet',
                description: 'eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [1,7],
                relations: [],
                checklist: [],
                attachments: [],
                comments: []
            },
            {
                id: 5,
                columnId: 2,
                columnPosition: 2,
                name: 'Lorem ipsum',
                description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [2],
                relations: [],
                checklist: [],
                attachments: [],
                comments: []
            },
            {
                id: 6,
                columnId: 2,
                columnPosition: 3,
                name: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                description: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [4,7],
                relations: [],
                checklist: [],
                attachments: [],
                comments: []
            },
        ]
    },
    {
        id: 3,
        name: 'Test project 3',
        description: 'this is just the description for test project 3. With some random words on the end to make it a little bit longer. Then there is some more text on the end that is completly random lol.',
        createdOn: '',
        image: 'https://picsum.photos/200',
        tags: [
            {id: 1, name: 'P1', description: 'highest level of priority', colour: '#ff4f4f'},
            {id: 2, name: 'P2', description: 'second highest level of priority', colour: '#ff824f'},
            {id: 3, name: 'P3', description: 'third highest level of priority', colour: '#ffc74f'},
            {id: 4, name: 'P4', description: 'second lowest level of priority', colour: '#c7ff4f'},
            {id: 5, name: 'P5', description: 'lowest level of priority', colour: '#6aff4f'},
            {id: 6, name: 'On Live', description: 'its on the live site', colour: '#1fc137'},
            {id: 7, name: 'Ready for Live', description: 'reaady to go on the live site', colour: '#c1891f'},
        ],
        columns: [
            { id: 1, name: 'Jan', positon: 0, color: '#bfbfbf'},
            { id: 2, name: 'December', positon: 1, color: '#f2f2f2'},
            { id: 3, name: 'November', positon: 2, color: '#9a0000'},
            { id: 4, name: 'May', positon: 3, color: '#9a8700'},
        ],
        tasks: [
            {
                id: 1,
                columnId: 1,
                columnPosition: 1,
                name: 'Add header',
                description: 'just a random description of task 1, but i have added some words onto the end to make the description a little longer',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [1,7],
                relations: [],
                checklist: [
                    {id: 1, description: 'blooping bloop', checked: false},
                    {id: 2, description: 'blap blap bloop', checked: true},
                    {id: 3, description: 'some text', checked: false},
                ],
                attachments: [],
                comments: []
            },
            {
                id: 2,
                columnId: 1,
                columnPosition: 2,
                name: 'Add footer',
                description: 'just a random description of task 2',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [2],
                relations: [1],
                checklist: [],
                attachments: [],
                comments: []
            },
            {
                id: 3,
                columnId: 1,
                columnPosition: 3,
                name: 'Add Newsletter',
                description: 'just a random description of task 3, then some extra text, maybe i should use lorem ipsum here?',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [1,7],
                relations: [],
                checklist: [],
                attachments: [],
                comments: []
            },
            {
                id: 4,
                columnId: 2,
                columnPosition: 1,
                name: 'Lorem ipsum dolor sit amet',
                description: 'eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [1,7],
                relations: [],
                checklist: [],
                attachments: [],
                comments: []
            },
            {
                id: 5,
                columnId: 2,
                columnPosition: 2,
                name: 'Lorem ipsum',
                description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [2],
                relations: [],
                checklist: [],
                attachments: [],
                comments: []
            },
            {
                id: 6,
                columnId: 2,
                columnPosition: 3,
                name: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                description: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio',
                dueDate: '2024,0,1',
                createdOn: '2023,11,1',
                updated: '2023,11,16',
                state: 'open',
                tags: [4,7],
                relations: [],
                checklist: [],
                attachments: [],
                comments: []
            },
        ]
    }
]
